### ISSUE TITLE
map_to_struct can't decode cell array containing maps

### ISSUE THREAD

**Issue by feanor12** [g-s-k/matlab-toml#23]
The map_to_struct script is quite handy, but it can't handle cell arrays of maps.
I think a simple `isa` check and a recursive call to the items that are map would solve this.

This happens when a toml file contains multiple [[name]] keys.

``` toml
[[test]]
a = 3

[[test]]
a=5
```
